### ISSUE TITLE
Set video aspect ratio

### ISSUE THREAD

**Issue by cloudjanak** [cedanmisquith/Tik-Tok-Video-Feed-Swift#1]

**Comment by cedanmisquith** [comment]
@cloudjanak could you provide more information regarding this issue ?

**Comment by cloudjanak** [comment]
<img width="1027" alt="Screenshot 2023-01-07 at 11 22 53 PM" src="https://user-images.githubusercontent.com/7457258/211163975-e82d6d9d-60ae-4f8b-8c8d-5a1f1e7dc4e0.png">

**Comment by cedanmisquith** [comment]
@cloudjanak Ahh okay. I get what you are saying. 
I have given a resize option to the video to fill the entire screen. If you want to retain the videos aspect ratio then you can do any one of these 2 options: 

**Option 1:**

- In `VideoLayers` file go to line number `16` and change it from 

`layer.videoGravity = AVLayerVideoGravity.resize`
to 
`layer.videoGravity = AVLayerVideoGravity.resizeAspect`

- In `VideoCustomCell` file go to line number 34 and do the same. 

**Option 2:**
You can also just comment out these lines in both the files so that the compiler will take the default which is the same as `resizeAspect`


I recommend the first option so that in the future if you need to modify this dynamically you will have a provision to do so. 

I hope this helps.
